### ISSUE TITLE
Firefox addon url is broken

### ISSUE THREAD

**Issue by Winns** [nuxt-company/vue-telescope-analyzer#34]
Firefox vue-telemetry addon url is broken, page not found.

### Reproduction Link

https://addons.mozilla.org/en-US/firefox/addon/vue-telemetry/

**Comment by bdrtsky** [comment]
Where did you found this url @Winns

**Comment by bdrtsky** [comment]
Should be fix now, thanks @Winns

**Comment by Winns** [comment]
"Add to Firefox" link at https://vuetelescope.com/ is still broken.

The link at https://vuetelescope.com/ is https://addons.mozilla.org/en-US/firefox/addon/vue-telemetry (**vue-telemetry**)
but correct one is https://addons.mozilla.org/en-US/firefox/addon/vue-telescope (**vue-telescope**)
